language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  global:
    - HOST_NAME: 'travis-ci'

before_install:
  - sudo apt-get install -qq python-lxml python-psycopg2

install: "pip install -r requirements-test.txt --use-mirrors"

script: paver test

after_success:
  - coveralls --verbose