language: python

virtualenv:
  system_site_packages: true

env:
  global:
    - HOST_NAME: 'travis-ci'
    - SECRET_KEY: 'SECRET_KEY'
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=coverage

services:
  - redis-server

before_install:
  - sudo apt-get install -qq python-lxml python-psycopg2

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
