- name: Omaha server
  hosts: 127.0.0.1
  connection: local
  vars:
    name: omaha-server-ansible
    region: eu-west-1
    instance_type: t2.micro
    keypair: omaha-server-ansible
    security_group: omaha-server-ansible
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: omaha-server
        description: omaha-server
        region: "{{ region }}"
      register: sg_omaha_server

    - name: Create security group
      local_action:
        module: ec2_group
        name: omaha-server-public
        description: omaha-server-public
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: "0.0.0.0/0"
      register: sg_omaha_server_public

    - name: Create security group
      local_action:
        module: ec2_group
        name: "omaha-db"
        description: omaha-db
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            group_id: "{{ sg_omaha_server.group_id }}"
      register: sg_db

    - name: Create keypair
      ec2_key:
        region: "{{region}}"
        name: "{{keypair}}"
      register: key
    - debug: var=key

    - name: create an IAM role
      local_action:
        module: iam
        region: "{{ region }}"
        iam_type: role
        name: omaha-server-s3-readonly
        state: present

    - name: create an IAM role policy
      local_action:
        module: iam_policy
        iam_name: omaha-server-s3-readonly
        iam_type: role
        policy_name: s3-private
        state: present
        policy_document: policies/s3_private.json


    - name: create S3 bucket
      local_action:
        module: s3
        bucket: omaha-server-ansible
        mode: create
        region: "{{ region }}"

    - name: create DB instance
      local_action:
        module: rds
        command: create
        instance_name: omaha-server
        db_engine: postgres
        instance_type: db.t2.small
        username: omaha
        password: 1nsecure
        security_groups: omaha-db
        tags:
          Application: omaha-server
